### ISSUE TITLE
Webpack warnings on  build after upgrade to gatsby v3

### ISSUE THREAD

**Issue by dan-mba** [hupe1980/gatsby-plugin-material-ui#65]
After updating to gatsby v3 I get a bunch of warnings on build

WebpackError: Unsafe builtin usage fs."insert name of fs command"
They are coming from calls to autoprefixer

gatsby v3 now uses webpack 5 which I think requires autoprefixer@10.2.4

**Comment by hupe1980** [comment]
Unfortunately, it seems to be more than that: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#using-fs-in-ssr

**Comment by daugsbi** [comment]
I've tried to upgrade today. With the following resolutions in the package.json, I still get the warning, but it looks like my project builds and work.

```json
{
  "resolutions": {
    "autoprefixer": "^10.2.4",
    "postcss": "^8.2.6",
    "cssnano": "^5.0.0-rc.1"
  }
}
```

The warning comes from browserslist. It probably tries to read package.json or .browserslistrc to load a users global configuration of supported browsers. This information is needed by autoprefixer, a postcss plugin.

Any idea how and where to fix this?

**Comment by hupe1980** [comment]
@pieh Do you have any hints how we can migrate to Gatsby3? Unfortunately, the instructions do not help us here

**Comment by kimbaudi** [comment]
I'm also getting the following error and warning messages on build after upgrading to gatsby v3.

```shell
 ERROR

(node:12256) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader  
(Use `node --trace-deprecation ...` to show where the warning was created)


 ERROR 

(node:12256) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

warn Unsafe builtin method was used, future builds will need to rebuild all pages
warn WebpackError: Unsafe builtin usage fs.existsSync
    at paulkode/node_modules/browserslist/node.js:38:1
    at paulkode/node_modules/browserslist/node.js:46:1
    at paulkode/node_modules/browserslist/node.js:305:1
    at paulkode/node_modules/browserslist/node.js:223:1
    at paulkode/node_modules/browserslist/index.js:411:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:63:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:46:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:98:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:109:1        
    at paulkode/node_modules/postcss/lib/lazy-result.js:288:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:274:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:298:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:343:1
    at paulkode/node_modules/gatsby-plugin-material-ui/autoprefixer.js:18:8
    at paulkode/node_modules/gatsby-plugin-material-ui/gatsby-ssr.js:54:65 
    at paulkode/.cache/api-runner-ssr.js:45:41

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.statSync   
    at paulkode/node_modules/browserslist/node.js:38:1
    at paulkode/node_modules/browserslist/node.js:46:1
    at paulkode/node_modules/browserslist/node.js:305:1
    at paulkode/node_modules/browserslist/node.js:223:1
    at paulkode/node_modules/browserslist/index.js:411:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:63:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:46:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:98:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:109:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:288:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:274:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:298:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:343:1
    at paulkode/node_modules/gatsby-plugin-material-ui/autoprefixer.js:18:8
    at paulkode/node_modules/gatsby-plugin-material-ui/gatsby-ssr.js:54:65
    at paulkode/.cache/api-runner-ssr.js:45:41

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.existsSync 
    at paulkode/node_modules/browserslist/node.js:38:1
    at paulkode/node_modules/browserslist/node.js:317:1
    at paulkode/node_modules/browserslist/node.js:49:1
    at paulkode/node_modules/browserslist/node.js:305:1
    at paulkode/node_modules/browserslist/node.js:223:1
    at paulkode/node_modules/browserslist/index.js:411:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:63:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:46:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:98:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:109:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:288:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:274:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:298:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:343:1
    at paulkode/node_modules/gatsby-plugin-material-ui/autoprefixer.js:18:8
    at paulkode/node_modules/gatsby-plugin-material-ui/gatsby-ssr.js:54:65

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.statSync   
    at paulkode/node_modules/browserslist/node.js:38:1
    at paulkode/node_modules/browserslist/node.js:317:1
    at paulkode/node_modules/browserslist/node.js:49:1
    at paulkode/node_modules/browserslist/node.js:305:1
    at paulkode/node_modules/browserslist/node.js:223:1
    at paulkode/node_modules/browserslist/index.js:411:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:63:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:46:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:98:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:109:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:288:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:274:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:298:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:343:1
    at paulkode/node_modules/gatsby-plugin-material-ui/autoprefixer.js:18:8
    at paulkode/node_modules/gatsby-plugin-material-ui/gatsby-ssr.js:54:65

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.readFileSync
    at paulkode/node_modules/browserslist/node.js:85:1 
    at paulkode/node_modules/browserslist/node.js:319:1
    at paulkode/node_modules/browserslist/node.js:49:1
    at paulkode/node_modules/browserslist/node.js:305:1
    at paulkode/node_modules/browserslist/node.js:223:1
    at paulkode/node_modules/browserslist/index.js:411:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:63:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:46:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:98:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:109:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:288:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:274:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:298:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:343:1
    at paulkode/node_modules/gatsby-plugin-material-ui/autoprefixer.js:18:8
    at paulkode/node_modules/gatsby-plugin-material-ui/gatsby-ssr.js:54:65

  83 |
  84 | function parsePackage (file) {
> 85 |   var config = JSON.parse(fs.readFileSync(file))
     | ^
  86 |   if (config.browserlist && !config.browserslist) {
  87 |     throw new BrowserslistError(
  88 |       '`browserlist` key instead of `browserslist` in ' + file

warn WebpackError: Unsafe builtin usage fs.existsSync 
    at paulkode/node_modules/browserslist/node.js:38:1
    at paulkode/node_modules/browserslist/node.js:328:1
    at paulkode/node_modules/browserslist/node.js:49:1
    at paulkode/node_modules/browserslist/node.js:305:1
    at paulkode/node_modules/browserslist/node.js:223:1
    at paulkode/node_modules/browserslist/index.js:411:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:63:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:46:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:98:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:109:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:288:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:274:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:298:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:343:1
    at paulkode/node_modules/gatsby-plugin-material-ui/autoprefixer.js:18:8
    at paulkode/node_modules/gatsby-plugin-material-ui/gatsby-ssr.js:54:65

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.existsSync 
    at paulkode/node_modules/browserslist/node.js:38:1
    at paulkode/node_modules/browserslist/node.js:332:8
    at paulkode/node_modules/browserslist/node.js:49:1
    at paulkode/node_modules/browserslist/node.js:305:1
    at paulkode/node_modules/browserslist/node.js:223:1
    at paulkode/node_modules/browserslist/index.js:411:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:63:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:46:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:98:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:109:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:288:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:274:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:298:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:343:1
    at paulkode/node_modules/gatsby-plugin-material-ui/autoprefixer.js:18:8
    at paulkode/node_modules/gatsby-plugin-material-ui/gatsby-ssr.js:54:65

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.existsSync 
    at paulkode/node_modules/browserslist/node.js:38:1
    at paulkode/node_modules/browserslist/node.js:199:1
    at paulkode/node_modules/browserslist/node.js:49:1
    at paulkode/node_modules/browserslist/node.js:197:1
    at paulkode/node_modules/browserslist/index.js:433:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:63:1
    at paulkode/node_modules/autoprefixer/lib/browsers.js:46:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:98:1
    at paulkode/node_modules/autoprefixer/lib/autoprefixer.js:109:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:288:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:274:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:298:1
    at paulkode/node_modules/postcss/lib/lazy-result.js:343:1
    at paulkode/node_modules/gatsby-plugin-material-ui/autoprefixer.js:18:8
    at paulkode/node_modules/gatsby-plugin-material-ui/gatsby-ssr.js:54:65
    at paulkode/.cache/api-runner-ssr.js:45:41

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }
```

**Comment by kimbaudi** [comment]
The warnings are caused by the following line of code in `gatsby-plugin-material-ui\src\autoprefixer.js`

https://github.com/hupe1980/gatsby-plugin-material-ui/blob/50e2f7aa61f94b8c9881a4c54af8ede8cc8e685d/gatsby-plugin-material-ui/src/autoprefixer.js#L8

Looking into the stack trace shows it is due to usage of `fs.*` in [browserlist/node.js](https://github.com/browserslist/browserslist/blob/c8dc18a681e50562f6c5a814e9bb7e864e4c7874/node.js#L38):

```js
  var result = fs.existsSync(file) && fs.statSync(file).isFile()
```

I'm not sure how to remove these warnings other than to disable autoprefixing (which is not ideal btw) in `gatsby-config.js`:

```js
{
  resolve: `gatsby-plugin-material-ui`,
  options: {
    disableAutoprefixing: true,
  },
},
```

**Comment by hupe1980** [comment]
Here's what I tried:
```javascript
import {browserlist} from 'gatsby'

const prefixer = postcss ([
    Autoprefixer ({overrideBrowserslist: browserlist}),
  ]);
```

Unfortunately, overrrideBrowserlist does not stop the lookup in browserlist/node.js

**Comment by daugsbi** [comment]
I've tried to load the package.json and the .browserslistrc with webpack and provide them to overrideBrowserslist.

I also changed the from parameter in the process from undefined to null.

See the work in progress here:
https://github.com/hupe1980/gatsby-plugin-material-ui/compare/master...daugsbi:master

It is working, but I don't know how to load the .browserslistrc optionally. If the file is not available, it throws an error.

**Comment by dan-mba** [comment]
@hupe1980 Can you try using a constant for browserlist just to see if works.

```javascript
const browserlist = [">2%"];

const prefixer = postcss ([
    Autoprefixer ({overrideBrowserlist: browserlist}),
]);
```

If it works with the const, maybe there is a way to get the browserlist in gatsby-node & cache it to use in gatsby-ssr.

**Comment by volKate** [comment]
@hupe1980 Hey, migrating to v3 I also face that [issue](https://github.com/gatsbyjs/gatsby/issues/29933). The `gatsby-plugin-material-ui` is the only one dependency I have that still require postcss7. Is it possible to update?

**Comment by pepijn-vanvlaanderen** [comment]
+1

**Comment by mariovde** [comment]
Got build errors, the likes of:

`warn Unsafe builtin method was used, future builds will need to rebuild all pages
warn WebpackError: Unsafe builtin usage fs.existsSync

**Comment by mpolinowski** [comment]
Confirmed - Warnings are gone after updating to `"gatsby-plugin-material-ui": "^3.0.0",`. Thank you!

**Comment by sergkudinov** [comment]
After updating to `"gatsby-plugin-material-ui": "^3.0.0"` I've got the same issue.

Installed packages:
- browserslist: 4.16.3
- autoprefixer: 10.2.5
- postcss: 8.2.9
- postcss-value-parser: 4.1.0

## Error:

```
warn Unsafe builtin method was used, future builds will need to rebuild all pages
warn WebpackError: Unsafe builtin usage fs.existsSync
    at nikita-docs/node_modules/browserslist/node.js:38:1
    at nikita-docs/node_modules/browserslist/node.js:46:1
    at nikita-docs/node_modules/browserslist/node.js:197:1
    at nikita-docs/node_modules/browserslist/index.js:433:1
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/browsers.js:54:12
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/browsers.js:42:26
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:41:20
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:86:25
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:247:29
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:245:18
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:270:16
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/processor.js:67:27
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/postcss/lib/container.js:138:18
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/postcss/lib/container.js:74:18
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/postcss/lib/container.js:60:16

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.statSync
    at nikita-docs/node_modules/browserslist/node.js:38:1
    at nikita-docs/node_modules/browserslist/node.js:46:1
    at nikita-docs/node_modules/browserslist/node.js:197:1
    at nikita-docs/node_modules/browserslist/index.js:433:1
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/browsers.js:54:12
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/browsers.js:42:26
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:41:20
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:86:25
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:247:29
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:245:18
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:270:16
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/processor.js:67:27
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/postcss/lib/container.js:138:18
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/postcss/lib/container.js:74:18
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/postcss/lib/container.js:60:16

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.existsSync
    at nikita-docs/node_modules/browserslist/node.js:38:1
    at nikita-docs/node_modules/browserslist/node.js:199:1
    at nikita-docs/node_modules/browserslist/node.js:49:1
    at nikita-docs/node_modules/browserslist/node.js:197:1
    at nikita-docs/node_modules/browserslist/index.js:433:1
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/browsers.js:54:12
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/browsers.js:42:26
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:41:20
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:86:25
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:247:29
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:245:18
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/supports.js:270:16
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/autoprefixer/lib/processor.js:67:27
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/postcss/lib/container.js:138:18
    at nikita-docs/node_modules/gatsby-plugin-material-ui/node_modules/postcss/lib/container.js:74:18

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

```

**Comment by iDVB** [comment]
Still getting this error in `gatsby-plugin-material-ui@3.0.1`

```
warn WebpackError: Unsafe builtin usage fs.statSync
    at myproject/node_modules/autoprefixer/node_modules/browserslist
/node.js:38:1
```

**Comment by dungle-scrubs** [comment]
I'm still getting the same error mentioned above for both versions 3.0.0 and 3.0.1 (a [stack post](https://stackoverflow.com/questions/67228518/unsafe-builtin-method-was-used-future-builds-will-need-to-rebuild-all-pages-g) recommended downgrading to 3.0.0 but it doesn't seem to help)

```
warning Unsafe builtin method was used, future builds will need to rebuild all pages
warning WebpackError: Unsafe builtin usage fs.existsSync
```

**Comment by dan-mba** [comment]
Do you have `browserslist` set in your `package.json`?

I use the following in mine & it builds with no error:
```json
"browserslist": [
  ">2%"
],
```

For more info on browserslist & the Gatsby defaults check the [Gatsby docs](https://www.gatsbyjs.com/docs/how-to/custom-configuration/browser-support/).

**Comment by dungle-scrubs** [comment]
@dan-mba I gave that a shot (on 3.0.0 and 3.0.1) but am still experiencing the same error unfortunately.  Here's the full error by the way:

```
warn Unsafe builtin method was used, future builds will need to rebuild all pages
warn WebpackError: Unsafe builtin usage fs.existsSync
    at new-website/node_modules/browserslist/node.js:38:1
    at new-website/node_modules/browserslist/node.js:46:1
    at new-website/node_modules/browserslist/node.js:197:1
    at new-website/node_modules/browserslist/index.js:433:1
    at new-website/node_modules/autoprefixer/lib/browsers.js:54:1
    at new-website/node_modules/autoprefixer/lib/browsers.js:42:1
    at new-website/node_modules/autoprefixer/lib/supports.js:41:1
    at new-website/node_modules/autoprefixer/lib/supports.js:86:1
    at new-website/node_modules/autoprefixer/lib/supports.js:247:1
    at new-website/node_modules/autoprefixer/lib/supports.js:245:1
    at new-website/node_modules/autoprefixer/lib/supports.js:270:1
    at new-website/node_modules/autoprefixer/lib/processor.js:67:1
    at new-website/node_modules/postcss/lib/container.js:138:1
    at new-website/node_modules/postcss/lib/container.js:74:1
    at new-website/node_modules/postcss/lib/container.js:60:1

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }
```

**Comment by emilwikstrom** [comment]
**Bump** This issue is currently preventing incremental builds on our site at Gatsby Cloud which affects our content and marketing teams since it takes a long time to get information published.

**Comment by dungle-scrubs** [comment]
> **Bump** This issue is currently preventing incremental builds on our site at Gatsby Cloud which affects our content and marketing teams since it takes a long time to get information published.

We're working on decoupling from Material-UI for Gatsby projects because of this issue. Build minutes are eaten up very fast for high volume shops without incremental builds. Hoping for a solution 🤞.

**Comment by emilwikstrom** [comment]
> We're working on decoupling from Material-UI for Gatsby projects because of this issue. Build minutes are eaten up very fast for high volume shops without incremental builds. Hoping for a solution 🤞.

I looked at the plugin code now and the issues seems to be that the plugin uses the autoprefixer package which in turn uses the file system. The real problem is that Material UI requires CSS postprocessing. This plugin actually follows the Material UI instructions to use autoprefixer (see [https://material-ui.com/getting-started/supported-platforms/#css-prefixing](url)). This means that a fix for Gatsby incremental builds would require this package to use an alternative CSS prefixer (one that does not use any "unsafe builtin" functions).

In my opinion a HTML/CSS ui library like Material UI should include all the CSS-prefixed they need for the features that they use. I also think it should make sense for them to list the features that requires CSS prefixing so that a user can know whether prefixing is needed or not.

**Comment by dan-mba** [comment]
I am the author of this issue.

My [repo](https://github.com/dan-mba/dan-mba.github.io/) which uses `gatsby-theme-material-ui` builds with no webpack warnings. Here is a link to the [gatsby-config](https://github.com/hupe1980/gatsby-theme-material-ui/blob/master/packages/gatsby-theme-material-ui/gatsby-config.js) it uses to include `gatsby-plugin-material-ui`. I only override the webfonts settings. 

I have no clue why some people are still seeing this issue. It is related to autoprefixer trying to determine your `browserslist` settings.

You might want to use `npm list autoprefixer` to see if any other plugins are also using autoprefixer.

Between gatsby & material-ui there are an infinite number of combinations that people could use. Mine seems to be one of the ones that works.  Trying to determine which combinations work & which don't is difficult because you aren't going to hear from those who don't see the message anymore after upgrading.

**Comment by jkananen** [comment]
The comments since Aug 10th 2021 should like be in https://github.com/hupe1980/gatsby-plugin-material-ui/issues/68

**Comment by dungle-scrubs** [comment]
@dan-mba Thanks for those links. I'm going to try to match your configuration as best I can to see if that helps.  Regarding running `npm list autoprefixer`, for me only `gatsby` and `gatsby-plugin-material-ui` are using it and they're both using `autoprefixer@10.3.1`.

If that doesn't help, I'll work on duplicating my repo into a public one to share.  Might take a couple of days.

**Comment by dungle-scrubs** [comment]
When I remove Mui's accordion component, the error goes away for me.  @emilwikstrom are you using the accordion?

**Comment by jkananen** [comment]
Good catch @dungle-scrubs ! I'm seeing the same. Thanks for the motivation to refactor this around this as we're about to do so anyway 😄

**Comment by emilwikstrom** [comment]
> When I remove Mui's accordion component, the error goes away for me. @emilwikstrom are you using the accordion?

Yes, we are also using Mui accordion and removing that seems to solve our problem!
Thank you @dungle-scrubs

**Comment by tudor2004** [comment]
I am having the exact same problem, any solutions without removing the Accordion?

**Comment by dungle-scrubs** [comment]
> I am having the exact same problem, any solutions without removing the Accordion?

Not that I know of. Finding an alternative for your accordions is probably your best bet.
